battle:
  - id: battleStartText
    text: "
▰▰▰▰▰▰ ⚔️ Начинается бой 🛡 ▰▰▰▰▰▰\n
🔴 ${firstCombatantName}[${firstCombatantLevel}] (${firstCombatantTypeEmoji}${firstCombatantClass}[${firstCombatantClassLevel}])\n
❤️${firstCombatantHP}/${firstCombatantMaxHP} ⚔️${firstCombatantAtk} 🛡${firstCombatantDef}\n
[${firstCombatantArmyTypeEmoji}] ${firstCombatantArmyName}[${firstCombatantArmyTier}]\n
💖${firstCombatantArmyHP}/${firstCombatantArmyMaxHP} 🪓${firstCombatantArmyAtk} 🪖${firstCombatantArmyDef}\n
🆚\n
🔵 ${secondCombatantName}[${secondCombatantLevel}] (${secondCombatantTypeEmoji}${secondCombatantClass}[${secondCombatantClassLevel}])\n
❤️${secondCombatantHP}/${secondCombatantMaxHP} ⚔️${secondCombatantAtk} 🛡${secondCombatantDef}\n
[${secondCombatantArmyTypeEmoji}] ${secondCombatantArmyName}[${secondCombatantArmyTier}]\n
💖${secondCombatantArmyHP}/${secondCombatantArmyMaxHP} 🪓${secondCombatantArmyAtk} 🪖${secondCombatantArmyDef}
"
  - id: battleTurnText
    text: "
▰▰▰▰▰▰ 🌀 Ход ${turn}▰▰▰▰▰▰\n
🔴 ${firstCombatantTypeEmoji}${firstCombatantName} [${firstCombatantArmyTypeEmoji}] командует:\n 
${firstCombatantLastSkill}\n
🔵 ${secondCombatantTypeEmoji}${secondCombatantName} [${secondCombatantArmyTypeEmoji}] командует:\n 
${secondCombatantLastSkill}\n
▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰\n
🔴 ${firstCombatantTypeEmoji}${firstCombatantName}  💥-${firstCombatantHeroDamageTaken} ❤️${firstCombatantHP}/${firstCombatantMaxHP}\n
[${firstCombatantArmyTypeEmojiAfter}] 💥-${firstCombatantArmyDamageTaken} 💖${firstCombatantArmyHP}/${firstCombatantArmyMaxHP}\n
🔵 ${secondCombatantTypeEmoji}${secondCombatantName}  💥-${secondCombatantHeroDamageTaken} ❤️${secondCombatantHP}/${secondCombatantMaxHP}\n
[${secondCombatantArmyTypeEmojiAfter}] 💥-${secondCombatantArmyDamageTaken} 💖${secondCombatantArmyHP}/${secondCombatantArmyMaxHP}  
"
  - id: yourTurnText
    text: "\n\nВаш ход:"
  #  - id: skillSelect
  #    inlineKeyboard:
  #      rows:
  #        - inlineKeyboardRow:
  #            - inlineKeyboardButton:
  #                text: "${skill1}"
  #                callbackData: "${skill1CallbackData}"
  #        - inlineKeyboardRow:
  #            - inlineKeyboardButton:
  #                text: "${skill2}"
  #                callbackData: "${skill2CallbackData}"
  #        - inlineKeyboardRow:
  #            - inlineKeyboardButton:
  #                text: "${skill3}"
  #                callbackData: "${skill3CallbackData}"
  - id: battleStart
    message:
      action: CREATE
      text: "${battleStartText}${yourTurnText}"
      replyKeyboard:
        inlineKeyboard:
            dynamicRows:
                id: charActiveSkills
  - id: battleStartLog
    message:
      action: CREATE
      text: "${battleStartText}"
  - id: battleTurn
    message:
      action: CREATE
      text: "${battleTurnText}${yourTurnText}"
      replyKeyboard:
        inlineKeyboard:
            dynamicRows:
                id: charActiveSkills
  - id: battleTurnLog
    message:
      action: CREATE
      text: "${battleTurnText}"
  - id: battleResult
    message:
      action: CREATE
      text: "
▰▰▰▰▰▰ Итог боя ▰▰▰▰▰▰\n
🔴 ${firstCombatantName}[${firstCombatantLevel}] (${firstCombatantTypeEmoji}${firstCombatantClass}[${firstCombatantClassLevel}]) ❤️${firstCombatantHP}/${firstCombatantMaxHP}\n
[${firstCombatantArmyTypeEmojiAfter}] ${firstCombatantArmyName}[${firstCombatantArmyTier}] 💖${firstCombatantArmyHP}/${firstCombatantArmyMaxHP}\n
${battleOutcome}\n
🔵  ${secondCombatantName}[${secondCombatantLevel}] (${secondCombatantTypeEmoji}${secondCombatantClass}[${secondCombatantClassLevel}]) ❤️${secondCombatantHP}/${secondCombatantMaxHP}\n
[${secondCombatantArmyTypeEmojiAfter}] ${secondCombatantArmyName}[${secondCombatantArmyTier}] 💖${secondCombatantArmyHP}/${secondCombatantArmyMaxHP}\n 
Награда:\n
${lootGained}
"
      replyKeyboard:
        inlineKeyboard:
          rows:
            - inlineKeyboardRow:
                - inlineKeyboardButton:
                    text: "Вернуться"
                    callbackData: "storyteller_main_menu"
